# Generated by Django 2.0.8 on 2018-11-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20181109_1225'),
        ('report', '0012_auto_20181113_1510'),
    ]

    operations = [
    ]
