# Generated by Django 2.0.8 on 2018-11-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_merge_20181121_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlFilterSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('mode', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='urlfilter',
            name='mode',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlfilter',
            name='url_filter_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_filter_url_filter_set', to='report.UrlFilterSet'),
        ),
    ]
